name: build-and-deploy

on: 
  push:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          persist-credentials: false

    - name: Build
      run: |
        yarn install
        make javascript
      
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@v0.12.0
      env:
        PAGES_BRANCH: gh-pages
        TOKEN: ${{ secrets.ACCESS_TOKEN }}